### HW6 (Linear Regression)

##### Netid: aadcosta
##### Seating Pin : 79

### Part 1: Linear Regression

In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import MinMaxScaler
import matplotlib.pyplot as plt
from sklearn.metrics import mean_squared_error

##### Extract features and label for the data

In [2]:
data = pd.read_csv('E:\MS\MS_studies\Sem_2\IntrotoML\HW3\\71-80.csv')

In [3]:
data = data.iloc[:, [3,4,5,6,7,8]]

In [4]:
data

    cit_2017  cit_2018  cit_2019  cit_2020  cit_2021  cit_2022
0        104        99       104        90        70        65
1         64        75        63        47        59        47
2        840       699       668       576       631       613
3         43        57        80        92        81        81
4          8        60        31       102       134       202
..       ...       ...       ...       ...       ...       ...
95       442       443       404       355       385       333
96      1307      1557      1814      1958      1926      1827
97       493       520       450       474       412       338
98        37        30        51        53        67        53
99         0         2        10        34       103       156

[100 rows x 6 columns]

##### Normalize the features[ Both X and Y]

In [5]:
scaler = MinMaxScaler()

scaled_arr = scaler.fit_transform(data)

In [6]:
data.columns

Index(['cit_2017', 'cit_2018', 'cit_2019', 'cit_2020', 'cit_2021', 'cit_2022'], dtype='object')

In [7]:
scaled_df = pd.DataFrame(scaled_arr, columns=data.columns[0:6])

In [8]:
scaled_df

    cit_2017  cit_2018  cit_2019  cit_2020  cit_2021  cit_2022
0   0.037763  0.033480  0.035167  0.027132  0.022774  0.021160
1   0.023239  0.025364  0.020891  0.013243  0.018979  0.015017
2   0.305011  0.236388  0.231546  0.184109  0.216356  0.208191
3   0.015614  0.019276  0.026811  0.027778  0.026570  0.026621
4   0.002905  0.020291  0.009749  0.031008  0.044859  0.067918
..       ...       ...       ...       ...       ...       ...
95  0.160494  0.149814  0.139624  0.112726  0.131470  0.112628
96  0.474582  0.526547  0.630571  0.630491  0.663216  0.622526
97  0.179012  0.175854  0.155641  0.151163  0.140787  0.114334
98  0.013435  0.010145  0.016713  0.015181  0.021739  0.017065
99  0.000000  0.000676  0.002437  0.009044  0.034161  0.052218

[100 rows x 6 columns]

##### Split the data into training and testing sets

In [9]:
trained_data, test_data = train_test_split(data,test_size=0.2, random_state=0)

In [10]:
scaler = MinMaxScaler()

scaled_arr = scaler.fit_transform(trained_data)

In [11]:
trained_data = pd.DataFrame(scaled_arr, columns=data.columns[0:6])

In [12]:
trained_data

    cit_2017  cit_2018  cit_2019  cit_2020  cit_2021  cit_2022
0   0.194989  0.157592  0.125087  0.090762  0.078756  0.066963
1   0.081699  0.096720  0.098258  0.091085  0.071503  0.089170
2   0.015614  0.019276  0.026132  0.027778  0.025561  0.025624
3   0.099855  0.099087  0.083624  0.079780  0.073575  0.075846
4   0.015977  0.018262  0.025087  0.028424  0.035233  0.026990
..       ...       ...       ...       ...       ...       ...
75  0.474582  0.526547  0.630314  0.630491  0.662867  0.622139
76  0.070806  0.076429  0.054355  0.063953  0.060794  0.064571
77  0.040668  0.064592  0.079443  0.073966  0.100518  0.122993
78  0.054466  0.108894  0.109059  0.094961  0.104663  0.111035
79  0.228758  0.221170  0.273868  0.267765  0.264594  0.240178

[80 rows x 6 columns]

In [13]:
X_train_scaled =  trained_data.iloc[:, [0,1,2,3,4]]
y_train_scaled = trained_data.iloc[:,[5]]

In [14]:
X_train_scaled

    cit_2017  cit_2018  cit_2019  cit_2020  cit_2021
0   0.194989  0.157592  0.125087  0.090762  0.078756
1   0.081699  0.096720  0.098258  0.091085  0.071503
2   0.015614  0.019276  0.026132  0.027778  0.025561
3   0.099855  0.099087  0.083624  0.079780  0.073575
4   0.015977  0.018262  0.025087  0.028424  0.035233
..       ...       ...       ...       ...       ...
75  0.474582  0.526547  0.630314  0.630491  0.662867
76  0.070806  0.076429  0.054355  0.063953  0.060794
77  0.040668  0.064592  0.079443  0.073966  0.100518
78  0.054466  0.108894  0.109059  0.094961  0.104663
79  0.228758  0.221170  0.273868  0.267765  0.264594

[80 rows x 5 columns]

##### Fit the linear model

In [15]:
model = LinearRegression()
model.fit(X_train_scaled, y_train_scaled)

LinearRegression()

##### Test the test set

In [16]:
scaled_arr = scaler.fit_transform(test_data)

In [17]:
test_data = pd.DataFrame(scaled_arr, columns=data.columns[0:6])

In [18]:
test_data

    cit_2017  cit_2018  cit_2019  cit_2020  cit_2021  cit_2022
0   0.087321  0.078143  0.085686  0.091837  0.136089  0.186480
1   0.000000  0.000000  0.000000  0.001020  0.000000  0.000000
2   1.000000  0.789354  0.647517  0.581633  0.632056  0.710956
3   0.086124  0.084938  0.090555  0.158163  0.135081  0.187646
4   0.038278  0.045300  0.062317  0.028571  0.041331  0.068765
5   0.002392  0.003398  0.033106  0.035714  0.035282  0.041958
6   0.069378  0.103058  0.122687  0.131633  0.156250  0.254079
7   0.181818  0.204983  0.183057  0.163265  0.265121  0.294872
8   0.113636  0.091733  0.074002  0.073469  0.053427  0.099068
9   0.523923  0.499434  0.390458  0.356122  0.384073  0.384615
10  0.075359  0.182333  0.245375  0.385714  0.553427  0.792541
11  0.289474  0.237826  0.192795  0.142857  0.131048  0.116550
12  0.040670  0.122310  0.176241  0.334694  0.532258  0.775058
13  0.000000  0.000000  0.006816  0.000000  0.010081  0.027972
14  0.325359  0.315968  0.309640  0.312245  0.369960  0.378788
15  0.047847  0.061155  0.048685  0.069388  0.056452  0.130536
16  0.017943  0.027180  0.024343  0.016327  0.017137  0.046620
17  0.269139  0.263873  0.252191  0.272449  0.294355  0.322844
18  0.881579  1.000000  1.000000  1.000000  1.000000  1.000000
19  0.505981  0.528879  0.420643  0.344898  0.336694  0.360140

In [19]:
X_test_scaled =  test_data.iloc[:, [0,1,2,3,4]]
y_test_scaled = test_data.iloc[:,[5]]

In [20]:
y_pred = model.predict(X_test_scaled)

In [21]:
y_pred_df = pd.DataFrame(y_pred,columns=["newval"],index=test_data.index)

In [22]:
y_pred

array([[0.15497621],
       [0.00461249],
       [0.58939363],
       [0.16111854],
       [0.02933441],
       [0.03703946],
       [0.16939177],
       [0.29204144],
       [0.04680794],
       [0.37057895],
       [0.68290841],
       [0.09686029],
       [0.68442187],
       [0.01390011],
       [0.3828311 ],
       [0.06643393],
       [0.01748557],
       [0.30639289],
       [0.96615677],
       [0.29008789]])

In [23]:
y_pred_df

      newval
0   0.154976
1   0.004612
2   0.589394
3   0.161119
4   0.029334
5   0.037039
6   0.169392
7   0.292041
8   0.046808
9   0.370579
10  0.682908
11  0.096860
12  0.684422
13  0.013900
14  0.382831
15  0.066434
16  0.017486
17  0.306393
18  0.966157
19  0.290088

In [24]:
test_data_actual = test_data_pred = test_data

In [25]:
test_data

    cit_2017  cit_2018  cit_2019  cit_2020  cit_2021  cit_2022
0   0.087321  0.078143  0.085686  0.091837  0.136089  0.186480
1   0.000000  0.000000  0.000000  0.001020  0.000000  0.000000
2   1.000000  0.789354  0.647517  0.581633  0.632056  0.710956
3   0.086124  0.084938  0.090555  0.158163  0.135081  0.187646
4   0.038278  0.045300  0.062317  0.028571  0.041331  0.068765
5   0.002392  0.003398  0.033106  0.035714  0.035282  0.041958
6   0.069378  0.103058  0.122687  0.131633  0.156250  0.254079
7   0.181818  0.204983  0.183057  0.163265  0.265121  0.294872
8   0.113636  0.091733  0.074002  0.073469  0.053427  0.099068
9   0.523923  0.499434  0.390458  0.356122  0.384073  0.384615
10  0.075359  0.182333  0.245375  0.385714  0.553427  0.792541
11  0.289474  0.237826  0.192795  0.142857  0.131048  0.116550
12  0.040670  0.122310  0.176241  0.334694  0.532258  0.775058
13  0.000000  0.000000  0.006816  0.000000  0.010081  0.027972
14  0.325359  0.315968  0.309640  0.312245  0.369960  0.378788
15  0.047847  0.061155  0.048685  0.069388  0.056452  0.130536
16  0.017943  0.027180  0.024343  0.016327  0.017137  0.046620
17  0.269139  0.263873  0.252191  0.272449  0.294355  0.322844
18  0.881579  1.000000  1.000000  1.000000  1.000000  1.000000
19  0.505981  0.528879  0.420643  0.344898  0.336694  0.360140

In [26]:
test_data_pred = merged_df = pd.concat([test_data, y_pred_df], axis=1)

In [27]:
test_data_pred

    cit_2017  cit_2018  cit_2019  cit_2020  cit_2021  cit_2022    newval
0   0.087321  0.078143  0.085686  0.091837  0.136089  0.186480  0.154976
1   0.000000  0.000000  0.000000  0.001020  0.000000  0.000000  0.004612
2   1.000000  0.789354  0.647517  0.581633  0.632056  0.710956  0.589394
3   0.086124  0.084938  0.090555  0.158163  0.135081  0.187646  0.161119
4   0.038278  0.045300  0.062317  0.028571  0.041331  0.068765  0.029334
5   0.002392  0.003398  0.033106  0.035714  0.035282  0.041958  0.037039
6   0.069378  0.103058  0.122687  0.131633  0.156250  0.254079  0.169392
7   0.181818  0.204983  0.183057  0.163265  0.265121  0.294872  0.292041
8   0.113636  0.091733  0.074002  0.073469  0.053427  0.099068  0.046808
9   0.523923  0.499434  0.390458  0.356122  0.384073  0.384615  0.370579
10  0.075359  0.182333  0.245375  0.385714  0.553427  0.792541  0.682908
11  0.289474  0.237826  0.192795  0.142857  0.131048  0.116550  0.096860
12  0.040670  0.122310  0.176241  0.334694  0.532258  0.775058  0.684422
13  0.000000  0.000000  0.006816  0.000000  0.010081  0.027972  0.013900
14  0.325359  0.315968  0.309640  0.312245  0.369960  0.378788  0.382831
15  0.047847  0.061155  0.048685  0.069388  0.056452  0.130536  0.066434
16  0.017943  0.027180  0.024343  0.016327  0.017137  0.046620  0.017486
17  0.269139  0.263873  0.252191  0.272449  0.294355  0.322844  0.306393
18  0.881579  1.000000  1.000000  1.000000  1.000000  1.000000  0.966157
19  0.505981  0.528879  0.420643  0.344898  0.336694  0.360140  0.290088

In [28]:
test_data_pred = test_data_pred.drop('cit_2022', axis=1)

In [29]:
test_data_pred = test_data_pred.rename(columns={'newval': 'cit_2022_pred'})

In [30]:
test_data_pred

    cit_2017  cit_2018  cit_2019  cit_2020  cit_2021  cit_2022_pred
0   0.087321  0.078143  0.085686  0.091837  0.136089       0.154976
1   0.000000  0.000000  0.000000  0.001020  0.000000       0.004612
2   1.000000  0.789354  0.647517  0.581633  0.632056       0.589394
3   0.086124  0.084938  0.090555  0.158163  0.135081       0.161119
4   0.038278  0.045300  0.062317  0.028571  0.041331       0.029334
5   0.002392  0.003398  0.033106  0.035714  0.035282       0.037039
6   0.069378  0.103058  0.122687  0.131633  0.156250       0.169392
7   0.181818  0.204983  0.183057  0.163265  0.265121       0.292041
8   0.113636  0.091733  0.074002  0.073469  0.053427       0.046808
9   0.523923  0.499434  0.390458  0.356122  0.384073       0.370579
10  0.075359  0.182333  0.245375  0.385714  0.553427       0.682908
11  0.289474  0.237826  0.192795  0.142857  0.131048       0.096860
12  0.040670  0.122310  0.176241  0.334694  0.532258       0.684422
13  0.000000  0.000000  0.006816  0.000000  0.010081       0.013900
14  0.325359  0.315968  0.309640  0.312245  0.369960       0.382831
15  0.047847  0.061155  0.048685  0.069388  0.056452       0.066434
16  0.017943  0.027180  0.024343  0.016327  0.017137       0.017486
17  0.269139  0.263873  0.252191  0.272449  0.294355       0.306393
18  0.881579  1.000000  1.000000  1.000000  1.000000       0.966157
19  0.505981  0.528879  0.420643  0.344898  0.336694       0.290088

In [31]:
test_data_actual

    cit_2017  cit_2018  cit_2019  cit_2020  cit_2021  cit_2022
0   0.087321  0.078143  0.085686  0.091837  0.136089  0.186480
1   0.000000  0.000000  0.000000  0.001020  0.000000  0.000000
2   1.000000  0.789354  0.647517  0.581633  0.632056  0.710956
3   0.086124  0.084938  0.090555  0.158163  0.135081  0.187646
4   0.038278  0.045300  0.062317  0.028571  0.041331  0.068765
5   0.002392  0.003398  0.033106  0.035714  0.035282  0.041958
6   0.069378  0.103058  0.122687  0.131633  0.156250  0.254079
7   0.181818  0.204983  0.183057  0.163265  0.265121  0.294872
8   0.113636  0.091733  0.074002  0.073469  0.053427  0.099068
9   0.523923  0.499434  0.390458  0.356122  0.384073  0.384615
10  0.075359  0.182333  0.245375  0.385714  0.553427  0.792541
11  0.289474  0.237826  0.192795  0.142857  0.131048  0.116550
12  0.040670  0.122310  0.176241  0.334694  0.532258  0.775058
13  0.000000  0.000000  0.006816  0.000000  0.010081  0.027972
14  0.325359  0.315968  0.309640  0.312245  0.369960  0.378788
15  0.047847  0.061155  0.048685  0.069388  0.056452  0.130536
16  0.017943  0.027180  0.024343  0.016327  0.017137  0.046620
17  0.269139  0.263873  0.252191  0.272449  0.294355  0.322844
18  0.881579  1.000000  1.000000  1.000000  1.000000  1.000000
19  0.505981  0.528879  0.420643  0.344898  0.336694  0.360140

In [32]:
test_actual_og = scaler.inverse_transform(test_data_actual)

In [33]:
y_actual = test_actual_og[:, -1]

In [34]:
y_actual

array([163.,   3., 613., 164.,  62.,  39., 221., 256.,  88., 333., 683.,
       103., 668.,  27., 328., 115.,  43., 280., 861., 312.])

In [35]:
test_pred_og = scaler.inverse_transform(test_data_pred)

In [36]:
y_pred = test_pred_og[:, -1]

In [37]:
y_pred

array([135.96959063,   6.95751923, 508.69973199, 141.23970819,
        28.16892318,  34.77985642, 148.33813603, 253.5715537 ,
        43.16120963, 320.95673848, 588.93541534,  86.10612738,
       590.2339623 ,  14.92629127, 331.46908289,  60.00031209,
        18.00261737, 265.88510308, 831.96251184, 251.89540624])

In [38]:
y_actual

array([163.,   3., 613., 164.,  62.,  39., 221., 256.,  88., 333., 683.,
       103., 668.,  27., 328., 115.,  43., 280., 861., 312.])

##### Calculate MSE

In [39]:
# Calculate squared differences
squared_errors = (y_actual - y_pred) ** 2
    
    # Calculate the mean of squared errors
mse = np.mean(squared_errors)
# Print the MSE
print(f"Mean Squared Error (MSE): {squared_errors}")

Mean Squared Error (MSE): [7.30643031e+02 1.56619585e+01 1.08785459e+04 5.18030883e+02
 1.14454176e+03 1.78096118e+01 5.27974648e+03 5.89735145e+00
 2.01051712e+03 1.45040148e+02 8.84814609e+03 2.85402932e+02
 6.04755662e+03 1.45774442e+02 1.20345361e+01 3.02496567e+03
 6.24869138e+02 1.99230315e+02 8.43175719e+02 3.61256219e+03]

In [40]:
mse

2219.507594917693

##### Calculate  Mean Absolute Error

In [41]:
mae = np.mean(np.abs(y_actual - y_pred))

In [42]:
res_df = pd.DataFrame({'y_act' : y_actual, 'y_pred' : y_pred})
# res_df['absolute_error'] = abs(res_df['y_act'] - res_df['y_pred'])

In [43]:
res_df['absolute_error'] = abs(res_df['y_act'] - res_df['y_pred'])

In [44]:
res_df.absolute_error.mean()

35.779670348067704

In [45]:
print(f"MAE for the above dataset using Linear Regression Model is {mae}")

MAE for the above dataset using Linear Regression Model is 35.779670348067704

##### Calculate Mean Absolute Percentage Error

In [46]:
mape = np.mean(np.abs((y_pred.flatten() - y_actual.flatten())/y_actual.flatten())) * 100

In [47]:
print(f"MAPE for the above dataset using Linear Regression Model is {mape}")

MAPE for the above dataset using Linear Regression Model is 27.72027163267112

In [48]:
test_actual_df = df = pd.DataFrame(test_actual_og,columns=['cit_2017','cit_2018','cit_2019','cit_2020','cit_2021','cit_2022_actual'])

In [49]:
test_pred_df = df = pd.DataFrame(test_pred_og,columns=['cit_2017','cit_2018','cit_2019','cit_2020','cit_2021','cit_2022_pred'])

##### Write the output to a csv file

In [50]:
test_actual_df['cit_2022_pred'] = test_pred_df['cit_2022_pred']

In [51]:
test_actual_df['absolute_error'] = abs(test_actual_df['cit_2022_actual'] - test_actual_df['cit_2022_pred'])
test_actual_df['abs_by_act'] = test_actual_df['absolute_error'] / test_actual_df['cit_2022_actual']

In [52]:
test_actual_df

,cit_2017,cit_2018,cit_2019,cit_2020,cit_2021,cit_2022_actual,cit_2022_pred,absolute_error,abs_by_act
0,77.0,71.0,91.0,96.0,139.0,163.0,135.969591,27.030409,0.165831
1,4.0,2.0,3.0,7.0,4.0,3.0,6.957519,3.957519,1.319173
2,840.0,699.0,668.0,576.0,631.0,613.0,508.699732,104.300268,0.170147
3,76.0,77.0,96.0,161.0,138.0,164.0,141.239708,22.760292,0.138782
4,36.0,42.0,67.0,34.0,45.0,62.0,28.168923,33.831077,0.545663
5,6.0,5.0,37.0,41.0,39.0,39.0,34.779856,4.220144,0.108209
6,62.0,93.0,129.0,135.0,159.0,221.0,148.338136,72.661864,0.328787
7,156.0,183.0,191.0,166.0,267.0,256.0,253.571554,2.428446,0.009486
8,99.0,83.0,79.0,78.0,57.0,88.0,43.161210,44.838790,0.509532
9,442.0,443.0,404.0,355.0,385.0,333.0,320.956738,12.043262,0.036166
10,67.0,163.0,255.0,384.0,553.0,683.0,588.935415,94.064585,0.137723
11,246.0,212.0,201.0,146.0,134.0,103.0,86.106127,16.893873,0.164018
12,38.0,110.0,184.0,334.0,532.0,668.0,590.233962,77.766038,0.116416
13,4.0,2.0,10.0,6.0,14.0,27.0,14.926291,12.073709,0.447174
14,276.0,281.0,321.0,312.0,371.0,328.0,331.469083,3.469083,0.010576
15,44.0,56.0,53.0,74.0,60.0,115.0,60.000312,54.999688,0.478258
16,19.0,26.0,28.0,22.0,21.0,43.0,18.002617,24.997383,0.581334
17,229.0,235.0,262.0,273.0,296.0,280.0,265.885103,14.114897,0.050410
18,741.0,885.0,1030.0,986.0,996.0,861.0,831.962512,29.037488,0.033725
19,427.0,469.0,435.0,344.0,338.0,312.0,251.895406,60.104594,0.192643

In [53]:
test_actual_df.to_csv('linear_regression_predictions.csv', index=False)